# Generated by Django 5.1.2 on 2024-10-16 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanager', '0002_subtask'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subtask',
            name='time_completed',
        ),
        migrations.RemoveField(
            model_name='task',
            name='time_completed',
        ),
    ]
